### ISSUE TITLE
Input error messages styles

### ISSUE THREAD

**Issue by iguissouma** [primefaces/ultima-ng#14]
Can you provide styles for error messages conform to material design specification and an example using the new grid css?

I have the following example:
```
<div class="ui-g-4 ui-md-4 ui-lg-4">
              <label for="name">Name</label>
            </div>
            <div class="ui-g-8 ui-md-8 ui-lg-8">
              <input formControlName="name" pInputText id="name" [(ngModel)]="user.name"/>
            </div>
            <div class="ui-g-12" *ngIf="!form.controls['name'].valid&&form.controls['name'].dirty">
              <div class="ui-message ui-messages-error ui-corner-all">
                Name is required
              </div>
            </div>
```
![2016-11-14_18h32_18](https://cloud.githubusercontent.com/assets/9085108/20275446/d900384a-aa98-11e6-944a-253b07dae439.png)

The style an positioning should be like below:
![2016-11-14_18h35_18](https://cloud.githubusercontent.com/assets/9085108/20275544/400af7be-aa99-11e6-9ba2-6c19cb913dde.png)

**Comment by mertsincan** [comment]
Fixed for next version. 
Test case;
```
<span class="md-inputfield">
   <input formControlName="name" pInputText id="name" [(ngModel)]="user.name"/>
   <label for="name">Name</label>
   <div class="ui-message ui-messages-error ui-corner-all" *ngIf="!form.controls['name'].valid&&form.controls['name'].dirty">
      Name is required
   </div>
</span>
```

![message_test](https://cloud.githubusercontent.com/assets/11868120/21137253/991b7186-c131-11e6-9041-67a5ef055e56.PNG)
