### ISSUE TITLE
Login when pressing ENTER

### ISSUE THREAD

**Issue by simdevmon** [primefaces/ultima-ng#16]
I think it would be more convenient if the login would also work when the ENTER button is pressed after filling out username and password. 
Currently the login button must be explicitly clicked: http://www.primefaces.org/ultima-ng/login/

**Comment by mertsincan** [comment]
I think this is a theme or layout issue. You can try it without ultima. Please use http://forum.primefaces.org/viewforum.php?f=35 for other issue.
