### ISSUE TITLE
Progress bar label is not is vertically not centralized

### ISSUE THREAD

**Issue by simdevmon** [primefaces/ultima-ng#19]
The progress bar label is not is vertically not centralized and almost hits the upper border. 

![2016-12-16_09h58_38](https://cloud.githubusercontent.com/assets/16277781/21257795/33b205ee-c37a-11e6-897b-4ae4911bb767.png)

It would be nicer if the label would be vertically in the center of the progress bar.

**Comment by Mrtcndkn** [comment]
It's fixed for next release.
