### ISSUE TITLE
Please don't look for the 1st child in layout.js for the wrapper

### ISSUE THREAD

**Issue by mrgoos** [primefaces/ultima-ng#25]
Hi,
in `layout.js` there's this code:
`this.wrapper = $(app.children[0]);`
In my main template where I put the menu code, if I put anything before `<div [ngClass]="{'layout-wrapper':true,'layout-compact':layoutCompact}">` The top bar menu button will not work.
It causes a bug that is very hard to find.
Please consider putting a dedicated class for the wrapper and selecting it in `layout.js`.
Thanks.

**Comment by cagataycivici** [comment]
Try with Ultima 2, please layout.js is gone as template is not based on query anymore, instead rewritten with native angular 2 apis.
