### ISSUE TITLE
Why Trial Version is unavailable?

### ISSUE THREAD

**Issue by saikiranmandhala** [primefaces/ultima-ng#63]
We are evaluating the prime-ng ultima, during this phase as we can not raise PO, we expect a trial version of premium templates as well. This is a problem for an employee working for a big organization as you know PO process(PO can be raised only after evaluation of premium templates/software/features)

The only way now is to go to browser DEV tools and get the CSS &HTML. It would be grade if you keep the trial versions along with the source code.

**Comment by sudheerj** [comment]
There are demo pages for themes and layouts. In my humble opinion that is quite enough for PO process over trial versions.

**Comment by saithis** [comment]
The demo pages don't show how good or bad the code is... and its unfortunatelly not that great :/

**Comment by cagataycivici** [comment]
It is common to provide a demo for evaluation purposes, that is how it works in template markets.
